### ISSUE TITLE
希望加入一个自定义UA的功能

### ISSUE THREAD

**Issue by pxw139** [Zxilly/UA2F#1]
如题

**Comment by Zxilly** [comment]
不太可能，因为他是按位替换UA，长度必须和原来的UA长度严格一致，这样的话就不用修改ACK了
你要是想换个字母自己改源码吧（

**Comment by pxw139** [comment]
准确的说，最好能自定义一部分内容
不足用其他字符补全，超出截取前面部分

**Comment by Zxilly** [comment]
麻烦，我觉得能用就行）
你可以自己改，就那几行
而且这会带来额外的运算，这程序已经够慢了。。。

**Comment by pxw139** [comment]
> 麻烦，我觉得能用就行）
> 你可以自己改，就那几行
> 而且这会带来额外的运算，这程序已经够慢了。。。

太艹,我本身是软路由跑着,性能基本不用考虑倒是

**Comment by pxw139** [comment]
也是,能用就行,现在还在用HTTP的东西我估计也不是什么重要的服务
有问题就有问题吧

(又 不 是 不 能 用
