### ISSUE TITLE
j1900编译openwrt无法开启ua2f

### ISSUE THREAD

**Issue by forgotfish** [Zxilly/UA2F#101]
遇到一个非常奇怪的问题，编译成功，ua2f初始化成功，但是“service ua2f start”无反应，网页端查询ua2f已启动,本地终端查询service反馈为“/etc/init.d/ua2f enabled stopped”内核日志无报错，系统日志查询“ua2f”为无
![C(IYWD BCY1ZZX$L9{12G3W](https://github.com/Zxilly/UA2F/assets/103720411/c86b5445-7a3c-44c6-b689-daa1c053ff00)
![N63H1 6Z93{)XY}@K4XJ%XP](https://github.com/Zxilly/UA2F/assets/103720411/b72225a5-7edb-4140-a482-15a6310cf78f)
![{`K7QSIUO3DYN$UVIF4K7B9](https://github.com/Zxilly/UA2F/assets/103720411/7f424df9-6acf-4c4c-bcc1-82d1816e5d5f)
![6TP99H(PZ2}ZO1MWU3})UXC](https://github.com/Zxilly/UA2F/assets/103720411/36fd4ac9-ec13-4c6f-b857-f3250e14c329)

**Comment by Zxilly** [comment]
系统日志你应该发最后那段而不是系统还在初始化的日志

**Comment by Zxilly** [comment]
`service ua2f start` 本来就没有回显

**Comment by forgotfish** [comment]
确实没有生效,同样的固件在上一台x86_64设备上生效了（上一台烧坏了，才换的这台）

![V$9BO %_9I_LHMAEXZT D(1](https://github.com/Zxilly/UA2F/assets/103720411/588968cc-d0f7-4680-9185-24888a3a12ee)

这张是系统日志的最后一段
![AZLV_{YTS$06GVVZD0E_OKI](https://github.com/Zxilly/UA2F/assets/103720411/c9008e8c-f7ad-4b7d-a37c-a8feeb13056f)

**Comment by Zxilly** [comment]
`command -v nft`看下输出

**Comment by forgotfish** [comment]
![7R(PU)OL1RQGE20G6~COQ@H](https://github.com/Zxilly/UA2F/assets/103720411/850e8047-1579-43ff-a3fc-05a89c058ce1)
没有反馈...

**Comment by Zxilly** [comment]
那 `cat /etc/config/ua2f`

**Comment by forgotfish** [comment]
![6WPM93CL(XI38N$RYGB4Q(4](https://github.com/Zxilly/UA2F/assets/103720411/8d24d226-3376-4a67-b10f-c4d6f983f98f)
如图

**Comment by Zxilly** [comment]
你没启用 ua2f
```
uci set ua2f.enabled.enabled=1
uci commit
serivce ua2f restart
```

**Comment by forgotfish** [comment]
![P7%J_SUFD`8@@CP00KXFP6Q](https://github.com/Zxilly/UA2F/assets/103720411/afb5679b-cbd7-464b-8a9a-a9de76589f3d)
好奇怪...

**Comment by Zxilly** [comment]
service 打错了，你自己改一下

**Comment by forgotfish** [comment]
哦哦哦，才看到，service

**Comment by forgotfish** [comment]
感谢感谢
