### ISSUE TITLE
ua2f不生效

### ISSUE THREAD

**Issue by Uranusual** [Zxilly/UA2F#102]
启动ua2f显示：
ptables v1.8.7 (legacy): unknown option "--queue-num"
Try `iptables -h' or 'iptables --help' for more information.

这是ua2f的设置
root@GL-MT3000:~# uci show ua2f
ua2f.enabled=ua2f
ua2f.enabled.enabled='1'
ua2f.firewall=ua2f
ua2f.firewall.handle_fw='1'
ua2f.firewall.handle_intranet='1'
ua2f.firewall.handle_tls='0'
ua2f.firewall.handle_mmtls='0'
ua2f.main=ua2f
ua2f.main.custom_ua='ffff'

**Comment by Zxilly** [comment]
没装 iptables-mod-nfqueue

**Comment by Zxilly** [comment]
跑一下 `opkg list-installed` 看一下结果，依赖里应该是指定了的

**Comment by Uranusual** [comment]
> 没装 iptables-mod-nfqueue

装了之后 没报错 但是还是没效果 是因为开了openclash的原因吗？

**Comment by Zxilly** [comment]
跑一下 `opkg list-installed` 和 `iptables -j NFQUEUE --help`，把结果发上来

**Comment by Zxilly** [comment]
`logread` 也发一下
