### ISSUE TITLE
编译后UA2F无法生效

### ISSUE THREAD

**Issue by hongyunxiao** [Zxilly/UA2F#104]
openwrt日志如下         版本openwrt-22.03原版
Fri Nov  3 20:30:23 2023 syslog.info UA2F[4961]: Statistics initialized.
Fri Nov  3 20:30:23 2023 syslog.info UA2F[4961]: Using embed user agent string: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.68
Fri Nov  3 20:30:23 2023 syslog.info UA2F[4961]: Handler initialized.
Fri Nov  3 20:30:23 2023 syslog.warn UA2F[4961]: Kernel does not support packet timestamps
Fri Nov  3 20:30:23 2023 syslog.info UA2F[4961]: Cache lock initialized
Fri Nov  3 20:30:23 2023 syslog.info UA2F[4961]: Cleanup thread created
已按照如下步骤编译内核
make kernel_menuconfig

# 然后将
# Networking support -> 
# Networking options -> 
# Network packet filtering framework (Netfilter) -> 
# Core Netfilter Configuration -> 
# Netfilter NFNETLINK interface
# Netfilter LOG over NFNETLINK interface
# Netfilter connection tracking support
# Connection tracking netlink interface
# NFQUEUE and NFLOG integration with Connection Tracking 打开编译内核

**Comment by Zxilly** [comment]
信息不足

**Comment by hongyunxiao** [comment]
请问还该向您提供哪些信息

**Comment by hongyunxiao** [comment]
防火墙中已经能看到UA2F
![捕获](https://github.com/Zxilly/UA2F/assets/113676706/8cea24b3-dd0b-447b-ad22-ffc4f63c4f27)

**Comment by Zxilly** [comment]
![image](https://github.com/Zxilly/UA2F/assets/31370133/c28481d0-6e91-4dbc-beae-036753aee7b6)
看起来已经有一部分流量被处理了，你是怎么判断无法生效的呢

**Comment by hongyunxiao** [comment]
![image](https://github.com/Zxilly/UA2F/assets/113676706/033c752a-8403-4f06-9f5d-5c1c22dc1402)

**Comment by hongyunxiao** [comment]
问题解决了，我无意间将ip动态伪装打开之后发现UA得到了修改，固件此处默认是关闭的
![image](https://github.com/Zxilly/UA2F/assets/113676706/0fec5660-d09b-4c44-920b-93207893ba19)
