### ISSUE TITLE
ua2f s in a crash loop

### ISSUE THREAD

**Issue by Lc113** [Zxilly/UA2F#105]
ua2f无法启动，系统日志出现：
Sat Nov  4 02:54:09 2023 daemon.info procd: Instance ua2f::ua2f s in a crash loop 6 crashes, 0 seconds since last crash

**Comment by Lc113** [comment]
安装的包：
root@OpenWrt:~# opkg list-installed
arptables-nft - 1.8.8-1
base-files - 1545-r24283-280d9dd758
bash - 5.2.15-1
busybox - 1.36.1-1
ca-bundle - 20230311-1
ca-certificates - 20230311-1
cgi-io - 2022-08-10-901b0f04-21
coreutils - 9.3-1
coreutils-nohup - 9.3-1
curl - 8.4.0-2
dnsmasq-full - 2.89-6
dropbear - 2022.82-5
ebtables-nft - 1.8.8-1
firewall4 - 2023-09-01-598d9fbb-1
fstools - 2023-02-28-bfe882d5-1
fwtool - 2019-11-12-8f7fe925-1
getrandom - 2022-08-13-4c7b720b-2
hostapd-common - 2023-09-08-e5ccbfc6-5
ip-full - 6.5.0-1
ipset - 7.17-1
iptables-mod-conntrack-extra - 1.8.8-1
iptables-mod-ipopt - 1.8.8-1
iptables-nft - 1.8.8-1
iw - 5.19-1
iwinfo - 2023-07-01-ca79f641-1
jansson4 - 2.14-3
jshn - 2023-05-23-75a3b870-1
jsonfilter - 2018-02-04-c7e938d6-1
kernel - 5.15.137-1-1e96c0adc826e7e9d7d8c1c19b5a5ebc
kmod-arptables - 5.15.137-1
kmod-cfg80211 - 5.15.137+6.5-1
kmod-crypto-aead - 5.15.137-1
kmod-crypto-ccm - 5.15.137-1
kmod-crypto-cmac - 5.15.137-1
kmod-crypto-crc32c - 5.15.137-1
kmod-crypto-ctr - 5.15.137-1
kmod-crypto-gcm - 5.15.137-1
kmod-crypto-gf128 - 5.15.137-1
kmod-crypto-ghash - 5.15.137-1
kmod-crypto-hash - 5.15.137-1
kmod-crypto-hmac - 5.15.137-1
kmod-crypto-manager - 5.15.137-1
kmod-crypto-null - 5.15.137-1
kmod-crypto-rng - 5.15.137-1
kmod-crypto-seqiv - 5.15.137-1
kmod-crypto-sha512 - 5.15.137-1
kmod-ebtables - 5.15.137-1
kmod-gpio-button-hotplug - 5.15.137-3
kmod-ip6tables - 5.15.137-1
kmod-ipt-conntrack - 5.15.137-1
kmod-ipt-conntrack-extra - 5.15.137-1
kmod-ipt-core - 5.15.137-1
kmod-ipt-ipopt - 5.15.137-1
kmod-ipt-ipset - 5.15.137-1
kmod-leds-gpio - 5.15.137-1
kmod-lib-crc-ccitt - 5.15.137-1
kmod-lib-crc32c - 5.15.137-1
kmod-mac80211 - 5.15.137+6.5-1
kmod-mt76-core - 5.15.137+2023-09-18-2afc7285-1
kmod-mt7603 - 5.15.137+2023-09-18-2afc7285-1
kmod-nf-conncount - 5.15.137-1
kmod-nf-conntrack - 5.15.137-1
kmod-nf-conntrack-netlink - 5.15.137-1
kmod-nf-conntrack6 - 5.15.137-1
kmod-nf-flow - 5.15.137-1
kmod-nf-ipt - 5.15.137-1
kmod-nf-ipt6 - 5.15.137-1
kmod-nf-log - 5.15.137-1
kmod-nf-log6 - 5.15.137-1
kmod-nf-nat - 5.15.137-1
kmod-nf-reject - 5.15.137-1
kmod-nf-reject6 - 5.15.137-1
kmod-nf-tproxy - 5.15.137-1
kmod-nfnetlink - 5.15.137-1
kmod-nfnetlink-queue - 5.15.137-1
kmod-nft-arp - 5.15.137-1
kmod-nft-bridge - 5.15.137-1
kmod-nft-compat - 5.15.137-1
kmod-nft-core - 5.15.137-1
kmod-nft-fib - 5.15.137-1
kmod-nft-nat - 5.15.137-1
kmod-nft-offload - 5.15.137-1
kmod-nft-queue - 5.15.137-1
kmod-nft-tproxy - 5.15.137-1
kmod-ppp - 5.15.137-1
kmod-pppoe - 5.15.137-1
kmod-pppox - 5.15.137-1
kmod-rt2x00-lib - 5.15.137+6.5-1
kmod-slhc - 5.15.137-1
kmod-tun - 5.15.137-1
libblobmsg-json20230523 - 2023-05-23-75a3b870-1
libbpf1 - 1.2.2-1
libc - 1.2.4-4
libcap - 2.69-1
libcap-bin - 2.69-1
libcurl4 - 8.4.0-2
libelf1 - 0.189-1
libgcc1 - 12.3.0-4
libgmp10 - 6.3.0-1
libipset13 - 7.17-1
libiptext-nft0 - 1.8.8-1
libiptext0 - 1.8.8-1
libiptext6-0 - 1.8.8-1
libiwinfo-data - 2023-07-01-ca79f641-1
libiwinfo20230701 - 2023-07-01-ca79f641-1
libjson-c5 - 0.17-1
libjson-script20230523 - 2023-05-23-75a3b870-1
liblua5.1.5 - 5.1.5-10
liblucihttp-lua - 2023-03-15-9b5b683f-1
liblucihttp-ucode - 2023-03-15-9b5b683f-1
liblucihttp0 - 2023-03-15-9b5b683f-1
libmbedtls12 - 2.28.5-1
libmnl0 - 1.0.5-1
libncurses6 - 6.4-2
libnetfilter-conntrack3 - 1.0.9-2
libnetfilter-queue1 - 1.0.5-4
libnettle8 - 3.9.1-1
libnfnetlink0 - 1.0.2-1
libnftnl11 - 1.2.6-1
libnghttp2-14 - 1.57.0-1
libnl-tiny1 - 2023-07-27-bc92a280-1
libpthread - 1.2.4-4
libreadline8 - 8.2-1
librt - 1.2.4-4
libruby3.2 - 3.2.2-2
libubox20230523 - 2023-05-23-75a3b870-1
libubus-lua - 2023-06-05-f787c97b-1
libubus20230605 - 2023-06-05-f787c97b-1
libuci20130104 - 2023-08-10-5781664d-1
libuclient20201210 - 2023-04-13-007d9454-1
libucode20230711 - 2023-10-19-07c03173-1
libustream-mbedtls20201210 - 2023-02-25-498f6e26-1
libxtables12 - 1.8.8-1
libyaml - 0.2.5-1
logd - 2022-08-13-4c7b720b-2
lua - 5.1.5-10
luci - git-23.305.38460-408ff05
luci-app-firewall - git-23.305.38460-408ff05
luci-app-openclash - 0.45.141-beta
luci-app-opkg - git-23.305.38460-408ff05
luci-base - git-23.305.38460-408ff05
luci-compat - git-23.305.38460-408ff05
luci-i18n-base-zh-cn - git-23.305.38460-408ff05
luci-i18n-firewall-zh-cn - git-23.305.38460-408ff05
luci-i18n-opkg-zh-cn - git-23.305.38460-408ff05
luci-lib-base - git-23.305.38460-408ff05
luci-lib-ip - git-23.305.38460-408ff05
luci-lib-jsonc - git-23.305.38460-408ff05
luci-lib-nixio - git-23.305.38460-408ff05
luci-light - git-23.305.38460-408ff05
luci-lua-runtime - git-23.305.38460-408ff05
luci-mod-admin-full - git-23.305.38460-408ff05
luci-mod-network - git-23.305.38460-408ff05
luci-mod-status - git-23.305.38460-408ff05
luci-mod-system - git-23.305.38460-408ff05
luci-proto-ipv6 - git-23.305.38460-408ff05
luci-proto-ppp - git-23.305.38460-408ff05
luci-theme-argon - 2.3.1
luci-theme-bootstrap - git-23.305.38460-408ff05
mtd - 26
netifd - 2023-10-20-5590a80e-2
nftables-json - 1.0.9-1
odhcp6c - 2023-05-12-bcd28363-20
odhcpd-ipv6only - 2023-10-24-d8118f6e-1
openwrt-keyring - 2022-03-25-62471e69-2
opkg - 2022-02-24-d038e5b6-2
ppp - 2.4.9.git-2021-01-04-5
ppp-mod-pppoe - 2.4.9.git-2021-01-04-5
procd - 2023-06-25-2db83655-3
procd-seccomp - 2023-06-25-2db83655-3
procd-ujail - 2023-06-25-2db83655-3
rpcd - 2023-07-01-c07ab2f9-1
rpcd-mod-file - 2023-07-01-c07ab2f9-1
rpcd-mod-iwinfo - 2023-07-01-c07ab2f9-1
rpcd-mod-luci - 20230123-1
rpcd-mod-rrdns - 20170710
rpcd-mod-ucode - 2023-07-01-c07ab2f9-1
ruby - 3.2.2-2
ruby-bigdecimal - 3.2.2-2
ruby-date - 3.2.2-2
ruby-digest - 3.2.2-2
ruby-enc - 3.2.2-2
ruby-forwardable - 3.2.2-2
ruby-pstore - 3.2.2-2
ruby-psych - 3.2.2-2
ruby-stringio - 3.2.2-2
ruby-yaml - 3.2.2-2
swconfig - 12
terminfo - 6.4-2
ua2f - 4.4.1-1
uboot-envtools - 2023.07.02-2
ubox - 2022-08-13-4c7b720b-2
ubus - 2023-06-05-f787c97b-1
ubusd - 2023-06-05-f787c97b-1
uci - 2023-08-10-5781664d-1
uclient-fetch - 2023-04-13-007d9454-1
ucode - 2023-10-19-07c03173-1
ucode-mod-fs - 2023-10-19-07c03173-1
ucode-mod-html - 1
ucode-mod-lua - 1
ucode-mod-math - 2023-10-19-07c03173-1
ucode-mod-nl80211 - 2023-10-19-07c03173-1
ucode-mod-rtnl - 2023-10-19-07c03173-1
ucode-mod-ubus - 2023-10-19-07c03173-1
ucode-mod-uci - 2023-10-19-07c03173-1
ucode-mod-uloop - 2023-10-19-07c03173-1
uhttpd - 2023-06-25-34a8a74d-1
uhttpd-mod-ubus - 2023-06-25-34a8a74d-1
unzip - 6.0-8
urandom-seed - 3
urngd - 2023-07-25-7aefb47b-1
usign - 2020-05-23-f1f65026-1
wireless-regdb - 2023.09.01-1
wpad-basic-mbedtls - 2023-09-08-e5ccbfc6-5
xtables-nft - 1.8.8-1
zlib - 1.3-1

**Comment by Lc113** [comment]
Openwrt23.05，小米路由器4C

**Comment by Zxilly** [comment]
`ulimit -c unlimited` 开启 coredump, 崩溃发生后上传 /tmp 目录下的 core 文件

**Comment by Lc113** [comment]
![5bb35792dadf6de1d39a4c6259f31bb](https://github.com/Zxilly/UA2F/assets/62469261/cb607c8c-b372-4c24-8cae-243070eb7e21)
![5bb35792dadf6de1d39a4c6259f31bb](https://github.com/Zxilly/UA2F/assets/62469261/fb87c353-a92a-4b1b-a619-caf24f22392f)
/tmp下无core文件

**Comment by Zxilly** [comment]
`cat /proc/sys/kernel/core_pattern` 看一下

**Comment by Zxilly** [comment]
然后打印一下配置文件 `cat /etc/config/ua2f`

**Comment by Lc113** [comment]
![1699100532087](https://github.com/Zxilly/UA2F/assets/62469261/33bb3e92-f004-4d9b-9bff-6ea9db3a6b95)

**Comment by Zxilly** [comment]
`ua2f --version` 执行正常吗，这是在判断配置读取是不是有问题

**Comment by Lc113** [comment]
确实
root@OpenWrt:~# ua2f --version
/usr/bin/ua2f: line 1: syntax error: unexpected "("

**Comment by Zxilly** [comment]
`ldd /usr/bin/ua2f` 看看，感觉你的这个文件根本不是可执行文件
![image](https://github.com/Zxilly/UA2F/assets/31370133/50de45a5-ba84-4465-b596-8d956bdeab10)

**Comment by Lc113** [comment]
![image](https://github.com/Zxilly/UA2F/assets/62469261/7ee323e4-a1c0-4c84-9761-b24ea1bae879)
惹啊，的确不是
