### ISSUE TITLE
ubuntu上编译ua2f4.4.1时编译报错

### ISSUE THREAD

**Issue by Vigai-qaq** [Zxilly/UA2F#107]
-- Found Git: /home/user/openwrt/staging_dir/host/bin/git (found version "2.25.1") 
-- Using version string: 4.4.1
-- Looking for __malloc_hook
CMake Error at /home/user/openwrt/package/UA2F/build/CMakeFiles/CMakeTmp/CMakeLists.txt:15 (add_executable):
  C_STANDARD is set to invalid value '17'

CMake Error at /home/user/openwrt/staging_dir/host/share/cmake-3.19/Modules/CheckSymbolExists.cmake:131 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  /home/user/openwrt/staging_dir/host/share/cmake-3.19/Modules/CheckSymbolExists.cmake:68 (__CHECK_SYMBOL_EXISTS_IMPL)
  CMakeLists.txt:48 (check_symbol_exists)

-- Configuring incomplete, errors occurred!
See also "/home/user/openwrt/package/UA2F/build/CMakeFiles/CMakeOutput.log".
make[3]: *** [Makefile:84: /home/user/openwrt/package/UA2F/openwrt/../.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[3]: Leaving directory '/home/user/openwrt/package/UA2F/openwrt'
time: package/UA2F/openwrt/compile#0.24#0.09#0.36
    ERROR: package/UA2F/openwrt failed to build.
make[2]: *** [package/Makefile:120: package/UA2F/openwrt/compile] Error 1
make[2]: Leaving directory '/home/user/openwrt'
make[1]: *** [package/Makefile:114: /home/user/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/user/openwrt'
make: *** [/home/user/openwrt/include/toplevel.mk:230：world] 错误 2

**Comment by Zxilly** [comment]
升级 cmake 至支持 C17 的版本
