### ISSUE TITLE
可以适配ramips/mt7621吗

### ISSUE THREAD

**Issue by Promising-star** [Zxilly/UA2F#112]
可以适配ramips/mt7621吗

型号 | Xiaomi Mi Router 4A Gigabit Edition v2

架构 | MediaTek MT7621 ver:1 eco:4

目标平台 | ramips/mt7621

固件版本 | OpenWrt 23.05.2 r23630-842932a63d / LuCI openwrt-23.05 branch git-23.306.39416-c86c256

内核版本 | 5.15.137

大佬辛苦了！

**Comment by Zxilly** [comment]
https://github.com/Zxilly/UA2F/releases/download/v4.4.2/ua2f_4.4.1-1_mipsel_24kc.ipk
