### ISSUE TITLE
自4.4.0起貌似不方便为非OpenWrt的Linux发行版编译

### ISSUE THREAD

**Issue by choking-chips** [Zxilly/UA2F#113]
我有个主机，装了个ArchLinux，用于处理流经校园网的流量。

当时直接cmake编译了4.2.2版本，没啥问题，安装和后续使用也很顺利。

现在想着这么久了要不更新一下，于是pull过来编译，发现缺少uci库。我很诧异，就去看了看commit，找到了在4.4.0版本添加的uci依赖。但是对于我的设备来说，不是很需要随时自定义UA（如果真需要就重新编译一下，也不是啥大问题），而且感觉uci也不能直接在OpenWrt外方便地使用（也可能是我了解不够多，没玩过软路由）。

那么现在，如果我想编译最新版UA2F，用于搭载这种非OpenWrt的Linux发行版的设备，请问有什么办法吗？

感谢您的项目！

**Comment by Zxilly** [comment]
v4.5.0 添加了相关支持
