### ISSUE TITLE
ua2f设置不生效

### ISSUE THREAD

**Issue by shiqu36** [Zxilly/UA2F#114]
raedme中的uci代码均可运行且不报错，同时也安装了luci-app-ua2f 可视化界面，在该界面中开启相应功能，全锥形nat和流量分载均关闭，设置后ua并未更改生效(路由开启了多拨和负载均衡)，，会不会是这个插件影响了？？

**Comment by Zxilly** [comment]
`luci-app-ua2f` 不是我写的，我也不清楚如何运行

**Comment by shiqu36** [comment]
> `luci-app-ua2f` 不是我写的，我也不清楚如何运行

luci-app-ua2f是ua2f的可视化界面，如果我不使用这个，使用ua2f也是一样的结果，全部设置成功后ua更改未生效，不知道是不是mwan3插件的影响，有过曾发生过的

**Comment by Zxilly** [comment]
会和mwan3冲突
