### ISSUE TITLE
在istoreos上安装无法正常安装依赖libnetfilter-quene导致内核panic重启

### ISSUE THREAD

**Issue by Mcxunyun666** [Zxilly/UA2F#115]
ua2f之前没出过iptables版本吗？或许你可以问下作者

_最初由 jjm2473 在 https://github.com/istoreos/istoreos/issues/1276#issuecomment-1899765082 发布_

想请教问下目前UA2F的工作机制是全局强制nft吗？还是两者都能兼容？谢谢了

**Comment by Zxilly** [comment]
都支持，优先使用 nftables

**Comment by Mcxunyun666** [comment]
> 都支持，优先使用 nftables
> 
> 

感觉有可能是libnetfilter-quene安装配置时拉了nft依赖然后强制安装导致的panic。回头我测试下看看，这个issue先开着留个路吧。感谢回答

**Comment by Zxilly** [comment]
https://github.com/Zxilly/UA2F/blob/5917acc7702e052e3ae4adfe25886036eab37d8b/openwrt/Makefile#L28

只会在你已经安装了的情况下添加依赖
