### ISSUE TITLE
如何在非OpenWRT的Linux发行版上使用

### ISSUE THREAD

**Issue by yinsel** [Zxilly/UA2F#116]
我不太熟悉iptables防火墙的规则，希望能有详细的配置教程，谢谢！

**Comment by Zxilly** [comment]
照着 https://github.com/Zxilly/UA2F/blob/master/openwrt/files/ua2f.init 改吧

**Comment by yinsel** [comment]
> 照着 https://github.com/Zxilly/UA2F/blob/master/openwrt/files/ua2f.init 改吧

好的，已经配置完成了，正常使用。
