### ISSUE TITLE
ua2f启动，但网站ua不变的情况

### ISSUE THREAD

**Issue by zhuan-ye** [Zxilly/UA2F#118]
Mon Mar 4 22:43:23 2024 syslog.info UA2F[4078]: Statistics initialized.
Mon Mar 4 22:43:23 2024 syslog.info UA2F[4078]: Custom user agent string not set, using default F-string.
Mon Mar 4 22:43:23 2024 syslog.info UA2F[4078]: Handler initialized
日志内容

turbo acc和NAT均关闭

**Comment by Zxilly** [comment]
提供的信息均正常，需要更多细节来判断具体错误

**Comment by zhuan-ye** [comment]
luci-app-advancedplus
luci-app-argon-config
luci-app-autoreboot
luci-app-cpufreq
luci-app-fan
luci-app-firewall
luci-app-mwan3
luci-app-opkg
luci-app-passwall
luci-app-ttydover the web	
luci-app-turboaccShortcut-FE	
luci-app-ua2f
luci-app-upnp
luci-app-wizard
luci-i18n-ttyd-zh-cn
这是插件页，有相冲突的吗

**Comment by Zxilly** [comment]
turboacc mwan3冲突

**Comment by zhuan-ye** [comment]
删除这些插件了，但是ua不变，有可能是拨号上网的问题吗

**Comment by zhuan-ye** [comment]
用的是openwrt-ai的默认包，软件包里下载的ua2f

**Comment by Zxilly** [comment]
没有看到有意义的信息，问问发行版的维护者吧🤷‍♂

**Comment by Zxilly** [comment]
还有没有啥hwnat/nss啥的，也找找
