### ISSUE TITLE
似乎会和mwan冲突，导致无法连接到接口

### ISSUE THREAD

**Issue by CoolLoong** [Zxilly/UA2F#13]

**Comment by Zxilly** [comment]
嗯，这是一个已知的问题，我也不打算修复，原因是在标记包的时候把mwan的标记覆盖了
________________________________
发件人: CoolLoong ***@***.***>
发送时间: 2021年5月28日 0:30
收件人: Zxilly/UA2F ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Zxilly/UA2F] 似乎会和mwan冲突，导致无法连接到接口 (#13)


―
