### ISSUE TITLE
部署UA2F后，Switch无法联网

### ISSUE THREAD

**Issue by AkiZZZZZ** [Zxilly/UA2F#131]
UA2F version: 4.5.0
开启UA2F后，Switch可以连上2.4G频段WiFi，但联网会报错2110-3150
关闭UA2F后，Switch可以连上2.4G频段WiFi，且正常联网。

**Comment by Zxilly** [comment]
我拿switch试了一下无法复现，但是UA2F确实可能导致此类bug，可以考虑自己加一条防火墙规则忽略switch。
