### ISSUE TITLE
报错 Signal Segmentation fault received, exiting...

### ISSUE THREAD

**Issue by PC12138-Z** [Zxilly/UA2F#136]
新版本UA2F  开启之后会拦截经过路由的所有数据，我关了ua2f就正常上网了，不知道是不是不兼容的问题，我的另一个路由就是没事，是正常的，之前旧版本（应该是4.6或者4.7版本）就没事两个路由都能正常使用。

我发现这问题之后我以为是新版本缺少依赖，所以我编译新固件的时候把ua2f也编译进去了，结果问题依旧，查log显示正常开启，实际上也是上不了网，里面有一条报错Kernel does not support packet timestamps，不知道是不是内核的原因

![屏幕截图 2024-09-12 095005](https://github.com/user-attachments/assets/9bda318e-b0a3-4d31-951c-7a63212d6b3d)
![屏幕截图 2024-09-12 094637](https://github.com/user-attachments/assets/b39beef0-3910-4920-85d4-144babab36f2)

**Comment by Zxilly** [comment]
有哪里出bug了，但是不太清楚什么原因

**Comment by Zxilly** [comment]
不过你是怎么编译的，为啥git相关的信息都是空的

**Comment by PC12138-Z** [comment]
> 不过你是怎么编译的，为啥git相关的信息都是空的

问题就是打开ua2f就上不了网 ，我重新安装了一遍，第一张图的复现不了了，log全部都是第二张图那样  Signal Segmentation fault received, exiting... ，也是打开就上不了网

**Comment by PC12138-Z** [comment]
> 不过你是怎么编译的，为啥git相关的信息都是空的

我把4.8.3到4.8.0版本都装了一遍，就4.8.0的不会显示git为空，4.8.3git为全空，4.8.2-4.8.1为Git branch 空。

最后一张为4.8.0，但是我安装4.8.0之后正常运行一会还是会报错 Signal Segmentation fault received, exiting...

![屏幕截图 2024-09-12 095005](https://github.com/user-attachments/assets/38718a37-0ac7-4b26-86e6-1934ab20b484)
![屏幕截图 2024-09-12 165514](https://github.com/user-attachments/assets/066e75bb-1f10-4de7-b1ff-a774e5f1e9e5)
![屏幕截图 2024-09-12 165809](https://github.com/user-attachments/assets/ecd79197-35c6-416e-8e1a-f00d85046f8e)
![屏幕截图 2024-09-12 170809](https://github.com/user-attachments/assets/3d611e2f-fc9d-4327-90ed-77acd3f8fac3)

**Comment by PC12138-Z** [comment]
> 有哪里出bug了，但是不太清

换成4.7.1就正常了，4.8.0以上版本都有问题，启用ua2f后，路由之后的设备会断网，但是路由没断网，估计是把经过路由的数据都拦截了。
不知道是不是 Kernel does not support packet timestamps 的原因，因为4.7.1没有报错Kernel does not support packet timestamps，4.8.0的git不会为空，但是会报Kernel does not support packet timestamps

**Comment by Zxilly** [comment]
`ulimit -c unlimited` 开启 coredump, 崩溃发生后上传 /tmp 目录下的 core 文件

**Comment by Zxilly** [comment]
4.8.0 以上主要是加了一个fallback支持，可能哪里没写好

**Comment by PC12138-Z** [comment]
> 命令行执行 `ulimit -c unlimited` 开启 coredump, 崩溃发生后上传 `/tmp` 目录下的 `.core` 文件和 `/usr/bin/ua2f`，打个 zip 包可以传 GitHub Issue 里

coredump 没有抓到东西，先把ua2f文件给你发了
[ua2f.zip](https://github.com/user-attachments/files/16979494/ua2f.zip)

**Comment by Zxilly** [comment]
```
ulimit -c unlimited
echo "/tmp/%e-%p-%t.core" > /proc/sys/kernel/core_pattern
echo "1" > /proc/sys/fs/suid_dumpable
```

如果没有core文件，试试以上命令

**Comment by PC12138-Z** [comment]
> ```
> ulimit -c unlimited
> echo "/tmp/%e-%p-%t.core" > /proc/sys/kernel/core_pattern
> echo "1" > /proc/sys/fs/suid_dumpable
> ```
> 
> 如果没有core文件，试试以上命令
还是没有core文件

**Comment by Zxilly** [comment]
用最新分支上的代码重新编译一下吧，之前错误的捕获了Segmentation fault信号

**Comment by PC12138-Z** [comment]
> 麻烦用最新分支上的代码重新编译一下吧，之前错误的捕获了Segmentation fault信号

试了还是报错，我想会不会是内核的原因，

我就把我另一个路由器刷了最新的分支编译的固件，内核从5.15.158升级到了5.15.164，装的ua2f最新版本，在没升级之前是不会报 git空 跟 Kernel does not support packet timestamps，升级之后就如下图，但是ua2f是正常起作用的，试了一下抓core文件也是没有

![屏幕截图 2024-09-13 105553](https://github.com/user-attachments/assets/7c82d1de-97a2-4489-9060-a5c4b1c1fe9f)


之前出问题的路由器内核也是最新5.15.164，估计是arm平台的问题了。

**Comment by Zxilly** [comment]
等我有空了加个内置的错误追踪吧

**Comment by JinXinYa** [comment]
同样的问题

**Comment by Zxilly** [comment]
@JinXinYa 请上传 coredump 文件

**Comment by JinXinYa** [comment]
没有coredump文件
![屏幕截图 2024-09-23 190016](https://github.com/user-attachments/assets/500ecde1-a1bc-4aa4-916e-cb6f9b502952)
![屏幕截图 2024-09-23 190054](https://github.com/user-attachments/assets/3f886683-13d3-4711-a02a-978112803589)

**Comment by Zxilly** [comment]
用最新的master分支上的代码编译不会捕获错误

**Comment by JinXinYa** [comment]
好的好的，刚刚又重新编译了一份，之前git信息是空的，现在有了。目前没有问题
![image](https://github.com/user-attachments/assets/6b17e890-7db9-4961-976a-9de574d4e702)

**Comment by 848657685** [comment]
> > 有哪里出bug了，但是不太清
> 
> 换成4.7.1就正常了，4.8.0以上版本都有问题，启用ua2f后，路由之后的设备会断网，但是路由没断网，估计是把经过路由的数据都拦截了。 不知道是不是 Kernel does not support packet timestamps 的原因，因为4.7.1没有报错Kernel does not support packet timestamps，4.8.0的git不会为空，但是会报Kernel does not support packet timestamps

感谢提供思路，安装旧版本就好了，跟59r 50m的东西 斗智斗勇几个晚上了

**Comment by Zxilly** [comment]
有能力的话还是传一下coredump，我这里无法复现，bug还是得修
