### ISSUE TITLE
可以加个...填上补齐后面的内容吗

### ISSUE THREAD

**Issue by alphime** [Zxilly/UA2F#137]
可以安装括号外判断空格有几个，一旦检测到...就补上空格后面的ua

**Comment by alphime** [comment]
我尝试实现下，但是发现在handle_packet里面的ua内容始终都是第一次登录的ua信息，而不是来自发送请求的UA，这是为什么

**Comment by alphime** [comment]
我是用的是函数里面的ua_start变量

**Comment by Zxilly** [comment]
能不能再解释下你想要什么，你是想要按照语义分割UA？

**Comment by alphime** [comment]
差不多，我自己实现了下遇到了个很奇怪的问题，不然你加我Q2328589870

**Comment by alphime** [comment]
![image](https://github.com/user-attachments/assets/4211165a-94b2-43e4-8cc2-d5a90bbeaa0f)
我是想自定义UA设置成Mozilla/5.0 (Windows NT 10.0; Win64; x64) 加请求UA的第一个括号`)`之后的内容，
但是我可以开始推测你代码ua_start变量是请求的ua内容，可我经验证之后，发现第一次连上网络的UA且一直保持不变
![image](https://github.com/user-attachments/assets/3f351814-f03b-49a1-8e17-71bb282200bc)
![image](https://github.com/user-attachments/assets/c36226f0-0a59-4192-8d16-86fd867a7ad4)

**Comment by Zxilly** [comment]
你没理解怎么处理的，去看看libnetfilter-queue的例子吧

**Comment by alphime** [comment]
你写的这个代码都是第一次的记录吗，要手动获取头部信息吗
