### ISSUE TITLE
我尝试编译新版本使用出现如下问题

### ISSUE THREAD

**Issue by alphime** [Zxilly/UA2F#138]
![image](https://github.com/user-attachments/assets/76a981b8-8579-46b2-b03b-b1acf6aebb29)

**Comment by Zxilly** [comment]
请参照 https://github.com/Zxilly/UA2F/issues/136 收集 core 文件上传

**Comment by alphime** [comment]
大佬，不然你帮我完善修复下我新写的新功能吧，本人实在是尽力了，排查了很久都没解决

**Comment by Zxilly** [comment]
我需要 coredump 文件才能确认错误

**Comment by alphime** [comment]
https://github.com/alphime/UA2F/commit/e2c8e4624a047ca679a45da55dea3f2b4b9beb3d

**Comment by alphime** [comment]
我感觉可能是我编译环境问题，你那边编译试下

**Comment by Zxilly** [comment]
替换的字符串必须长度一致

**Comment by alphime** [comment]
> 替换的字符串必须长度一致

我是后面补空格，这个方案不行吗？你开辟的是65536空间，后面应该读的到吧

**Comment by Zxilly** [comment]
请学习TCP协议中的ACK部分

**Comment by alphime** [comment]
![image](https://github.com/user-attachments/assets/3ba191df-ad08-4e8e-80ce-3d29be06ac3d)
![image](https://github.com/user-attachments/assets/3d881353-6520-41b4-b403-b9eab1b924a8)
![image](https://github.com/user-attachments/assets/b1a3c470-33bc-4c4c-b741-2634966fe47b)

好像不是这个问题啊，一样出现问题

**Comment by Zxilly** [comment]
你写的代码你问我干啥，你自己写的空指针

**Comment by alphime** [comment]
好吧想寻求你帮助下，我自己来吧
