### ISSUE TITLE
直接安装ipk为什么显示架构不对啊

### ISSUE THREAD

**Issue by polarcue** [Zxilly/UA2F#139]
cpu model 显示mips 24kc 选择了mip24kc的ipk
但还是说不兼容
![%S 4)4O{}BYI7XP063D7%4N](https://github.com/user-attachments/assets/5117982a-b550-4314-83bf-5108bf0ac511)
![{O0H0FOAREJ4UG J4WC49Z3](https://github.com/user-attachments/assets/80f17d13-19d0-4a9a-8755-d1808ae1ec4c)
![Y@VX879H5}0ZI5BB8`PZDLF](https://github.com/user-attachments/assets/ad31028e-9978-4019-a705-192571230111)

**Comment by Zxilly** [comment]
因为没有安装所需要的依赖

**Comment by polarcue** [comment]
> 因为没有安装所需要的依赖

我安装了netfilter-queue1.0,还是不行
确实一两不应该的dependencies吗

**Comment by Zxilly** [comment]
opkg 老毛病了，不管什么问题都报这个错。搞不明白就编译安装吧
