### ISSUE TITLE
UA2F中系统日志显示异常

### ISSUE THREAD

**Issue by tonytt0624** [Zxilly/UA2F#14]
Fri May 28 08:12:01 2021 syslog.info UA2F[1984]: UA2F has handled 385024 ua http, 103544050 tcp. Set 385024 mark and 7 noUA mark in 5 days, 20 hours, 3 minutes and 53 seconds
Fri May 28 08:13:33 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:33 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:33 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:33 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:34 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:36 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:36 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:36 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:37 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:37 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:37 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:37 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:37 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:38 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:38 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:40 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:41 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:41 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:41 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:41 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:42 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:42 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:42 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:43 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:43 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:44 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:44 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:44 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:45 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:45 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:46 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:47 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:49 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:49 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:53 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:53 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:13:57 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:14:01 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:14:09 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:14:14 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:14:17 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:14:41 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:14:47 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:14:49 2021 syslog.warn UA2F[1984]: UA overflow
Fri May 28 08:58:13 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 08:58:13 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 09:00:17 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 09:00:17 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 09:58:14 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 09:58:14 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 10:00:17 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 10:00:17 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 10:58:14 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 10:58:14 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 11:00:17 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 11:00:17 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 11:58:14 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 11:58:14 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 12:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 12:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 12:58:14 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 12:58:14 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 13:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 13:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 13:58:14 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 13:58:14 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 14:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 14:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 14:28:35 2021 syslog.info UA2F[1984]: UA2F has handled 393216 ua http, 103860581 tcp. Set 393216 mark and 7 noUA mark in 6 days, 2 hours, 20 minutes and 27 seconds
Fri May 28 14:58:14 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 14:58:14 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 15:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 15:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 15:58:14 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 15:58:14 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 16:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 16:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 16:33:39 2021 syslog.err UA2F[1984]: Catch SIGSEGV at breakpoint 4 and breakpoint2 5
Fri May 28 16:33:39 2021 syslog.alert UA2F[1984]: Meet fatal error, try to restart.
Fri May 28 16:33:39 2021 user.err : Child sucide.
Fri May 28 16:33:39 2021 user.notice : Try to start UA2F processor at [15310].
Fri May 28 16:33:39 2021 user.notice : UA2F processor start at [15310].
Fri May 28 16:33:39 2021 syslog.notice UA2F[15310]: Pipset inited.
Fri May 28 16:33:39 2021 syslog.notice UA2F[15310]: UA2F has inited successful.
Fri May 28 16:33:39 2021 syslog.err UA2F[15310]: Catch SIGSEGV at breakpoint 4 and breakpoint2 5
Fri May 28 16:33:39 2021 syslog.alert UA2F[15310]: Meet fatal error, try to restart.
Fri May 28 16:33:39 2021 user.err : Child sucide.
Fri May 28 16:33:39 2021 user.notice : Try to start UA2F processor at [15311].
Fri May 28 16:33:39 2021 user.notice : UA2F processor start at [15311].
Fri May 28 16:33:39 2021 syslog.notice UA2F[15311]: Pipset inited.
Fri May 28 16:33:39 2021 syslog.notice UA2F[15311]: UA2F has inited successful.
Fri May 28 16:33:39 2021 syslog.err UA2F[15311]: Catch SIGSEGV at breakpoint 4 and breakpoint2 5
Fri May 28 16:33:39 2021 syslog.alert UA2F[15311]: Meet fatal error, try to restart.
Fri May 28 16:33:39 2021 user.err : Child sucide.
Fri May 28 16:33:39 2021 user.notice : Try to start UA2F processor at [15312].
Fri May 28 16:33:39 2021 user.notice : UA2F processor start at [15312].
Fri May 28 16:33:39 2021 syslog.notice UA2F[15312]: Pipset inited.
Fri May 28 16:33:39 2021 syslog.notice UA2F[15312]: UA2F has inited successful.
Fri May 28 16:33:40 2021 syslog.err UA2F[15312]: Catch SIGSEGV at breakpoint 4 and breakpoint2 0
Fri May 28 16:33:40 2021 syslog.alert UA2F[15312]: Meet fatal error, try to restart.
Fri May 28 16:33:40 2021 user.err : Child sucide.
Fri May 28 16:33:40 2021 user.notice : Try to start UA2F processor at [15316].
Fri May 28 16:33:40 2021 user.notice : UA2F processor start at [15316].
Fri May 28 16:33:40 2021 syslog.notice UA2F[15316]: Pipset inited.
Fri May 28 16:33:40 2021 syslog.notice UA2F[15316]: UA2F has inited successful.
Fri May 28 16:33:41 2021 syslog.err UA2F[15316]: Catch SIGSEGV at breakpoint 4 and breakpoint2 5
Fri May 28 16:33:41 2021 syslog.alert UA2F[15316]: Meet fatal error, try to restart.
Fri May 28 16:33:41 2021 user.err : Child sucide.
Fri May 28 16:33:41 2021 user.notice : Try to start UA2F processor at [15324].
Fri May 28 16:33:41 2021 user.notice : UA2F processor start at [15324].
Fri May 28 16:33:41 2021 syslog.notice UA2F[15324]: Pipset inited.
Fri May 28 16:33:41 2021 syslog.notice UA2F[15324]: UA2F has inited successful.
Fri May 28 16:33:43 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:43 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:43 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:43 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:43 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:43 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:43 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:44 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:44 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:45 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:46 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:47 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:49 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:49 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:49 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:50 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 16:33:55 2021 syslog.info UA2F[15324]: UA2F has handled 8 ua http, 135 tcp. Set 8 mark and 0 noUA mark in 14 seconds
Fri May 28 16:34:11 2021 syslog.info UA2F[15324]: UA2F has handled 16 ua http, 2705 tcp. Set 16 mark and 0 noUA mark in 30 seconds
Fri May 28 16:34:25 2021 syslog.info UA2F[15324]: UA2F has handled 32 ua http, 3522 tcp. Set 32 mark and 0 noUA mark in 44 seconds
Fri May 28 16:34:39 2021 syslog.info UA2F[15324]: UA2F has handled 64 ua http, 3953 tcp. Set 64 mark and 0 noUA mark in 58 seconds
Fri May 28 16:35:18 2021 syslog.info UA2F[15324]: UA2F has handled 128 ua http, 4706 tcp. Set 128 mark and 0 noUA mark in 1 minutes and 37 seconds
Fri May 28 16:36:55 2021 syslog.info UA2F[15324]: UA2F has handled 256 ua http, 9199 tcp. Set 256 mark and 0 noUA mark in 3 minutes and 14 seconds
Fri May 28 16:41:01 2021 syslog.info UA2F[15324]: UA2F has handled 512 ua http, 28505 tcp. Set 512 mark and 0 noUA mark in 7 minutes and 20 seconds
Fri May 28 16:44:57 2021 syslog.info UA2F[15324]: UA2F has handled 1024 ua http, 53095 tcp. Set 1024 mark and 0 noUA mark in 11 minutes and 16 seconds
Fri May 28 16:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 16:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 17:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 17:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 17:39:25 2021 syslog.info UA2F[15324]: UA2F has handled 2048 ua http, 378396 tcp. Set 2048 mark and 0 noUA mark in 1 hours, 5 minutes and 44 seconds
Fri May 28 17:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 17:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 18:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 18:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 18:08:10 2021 syslog.info UA2F[15324]: UA2F has handled 4096 ua http, 706607 tcp. Set 4096 mark and 0 noUA mark in 1 hours, 34 minutes and 29 seconds
Fri May 28 18:11:59 2021 syslog.info UA2F[15324]: UA2F has handled 8192 ua http, 922614 tcp. Set 8192 mark and 0 noUA mark in 1 hours, 38 minutes and 18 seconds
Fri May 28 18:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 18:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 19:00:19 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 19:00:19 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 19:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 19:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 20:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 20:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 20:20:58 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:20:58 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:20:58 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:20:59 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:00 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:05 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:05 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:05 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:06 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:07 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:12 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:12 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:12 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:13 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:14 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:18 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:19 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:19 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:21:21 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:22:13 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:13 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:13 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:14 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:14 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:20 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:20 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:20 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:20 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:21 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:26 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:26 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:26 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:27 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:28 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:33 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:33 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:34 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:22:34 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:04 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:04 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:04 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:04 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:05 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:10 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:10 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:10 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:11 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:12 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:16 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:16 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:16 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:17 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:18 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:22 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:22 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:22 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:23 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:23:24 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:30 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:30 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:30 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:30 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:31 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:36 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:36 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:36 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:37 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:38 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:41 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:24:41 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:24:41 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:24:41 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:24:42 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:24:44 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:44 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:44 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:45 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:46 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:47 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:24:47 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:24:47 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:24:48 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:24:49 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:24:50 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:50 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:50 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:51 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:52 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:24:54 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:24:54 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:24:54 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:24:55 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:24:56 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:25:00 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:25:00 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:25:00 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:25:01 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:25:02 2021 syslog.warn UA2F[15324]: Offset overflow
Fri May 28 20:27:37 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:37 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:37 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:38 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:38 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:43 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:43 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:43 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:44 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:45 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:49 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:49 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:49 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:50 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:51 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:55 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:55 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:56 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:56 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:27:57 2021 syslog.warn UA2F[15324]: UA overflow
Fri May 28 20:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 20:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 21:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 21:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 21:01:47 2021 syslog.info UA2F[15324]: UA2F has handled 16384 ua http, 2570311 tcp. Set 16384 mark and 0 noUA mark in 4 hours, 28 minutes and 6 seconds
Fri May 28 21:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 21:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 22:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 22:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 22:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 22:58:16 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Fri May 28 23:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Fri May 28 23:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Fri May 28 23:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Fri May 28 23:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Sat May 29 00:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Sat May 29 00:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Sat May 29 00:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: sending renew to 10.217.31.254
Sat May 29 00:58:15 2021 daemon.notice netifd: wan (7097): udhcpc: lease of 10.217.20.137 obtained, lease time 7200
Sat May 29 01:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: sending renew to 10.217.31.254
Sat May 29 01:00:18 2021 daemon.notice netifd: wan2 (12127): udhcpc: lease of 10.217.20.138 obtained, lease time 7200
Sat May 29 01:57:36 2021 syslog.info UA2F[15324]: UA2F has handled 24576 ua http, 3436524 tcp. Set 24576 mark and 0 noUA mark in 9 hours, 23 minutes and 55 seconds

**Comment by Zxilly** [comment]
UA Overflow是报错，说明遇到了预料之外的情况
设计中，这个提示应该永远不会出现
如果可以的话，能发一下你的路由器抓包吗？用tcpdump，我才有可能去排查

**Comment by tonytt0624** [comment]
请稍等一会，安装tcpdump遇到了一些未知问题，正在解决。。。

**Comment by tonytt0624** [comment]
[tonytt.zip](https://github.com/Zxilly/UA2F/files/6564443/tonytt.zip)
