### ISSUE TITLE
v4.7.0到4.8.3版本，性能较低，很容易被校园网检测到

### ISSUE THREAD

**Issue by PC12138-Z** [Zxilly/UA2F#140]
应该是与4,7,0更新的内容有关系
4.6.2之前的版本则正常，4.6.3版本在我这边是有bug的

**Comment by Zxilly** [comment]
缺乏信息，无法修复

**Comment by Zxilly** [comment]
可以看看 log 是不是 fallback 到无 conntrack 模式了

**Comment by PC12138-Z** [comment]
> 可以看看 log 是不是 fallback 到无 conntrack 模式了

跟fallback没关系，
4.7.0不是更新了可以在没有启用 NETFILTER_NETLINK_GLUE_CT 的内核上运行吗，是不是跟禁用了缓存有关系

**Comment by Zxilly** [comment]
所以让你看log，看看是不是fallback了，检测到无法使用缓存才会自动禁用

**Comment by PC12138-Z** [comment]
> 所以让你看log，看看是不是fallback了，检测到无法使用缓存才会自动禁用

![{FA28CE0C-1246-4730-A6D0-D26A4E3E04DA}](https://github.com/user-attachments/assets/08259217-9df9-4170-9d51-b258ca336c7c)

**Comment by Zxilly** [comment]
发完整的，这个不是

**Comment by PC12138-Z** [comment]
> 发完整的，这个不是
