### ISSUE TITLE
大佬觉得这个项目怎么样

### ISSUE THREAD

**Issue by huhu415** [Zxilly/UA2F#141]
有什么缺点, 值得改进一下的. [uaProxy](https://github.com/huhu415/uaProxy)

**Comment by Zxilly** [comment]
你这编译出来都8M了，我那时候用的路由器整个ROM都放不下你这一个程序

**Comment by huhu415** [comment]
现在普遍路由器不都是128M么, 比如100块钱的ac2100红米的.

**Comment by Zxilly** [comment]
不太清楚，毕业以后我都不怎么碰这一块了
