### ISSUE TITLE
wrt默认的一个设置导致ua2f

### ISSUE THREAD

**Issue by 848657685** [Zxilly/UA2F#143]
我使用的是openwrt.ai在线编辑的固件在固件其他设置默认不变的情况下，利用网站检测ua2f是否生效一直刷新只有短暂的一会生效，在查看了防火墙ua2f的流量后试出了

https://github.com/user-attachments/assets/4af19a83-95ff-4b8d-b690-f96fa5f12518

![QQ截图20241122193823](https://github.com/user-attachments/assets/5a8c62fe-53e3-4deb-aa74-c947629df113)
关闭这个选项便可以让ua2f生效。请教下佬这个设置怎么干扰了ua2f的运行。

**Comment by Zxilly** [comment]
启用了offload以后，流量不会通过nfqueue，因此ua2f无法工作
