### ISSUE TITLE
不严重的报错syslog.warn UA2F[3874]: Received non-tcp packet. You may set wrong firewall rules.

### ISSUE THREAD

**Issue by YeWenxuan64** [Zxilly/UA2F#148]
在手贱升级ua2f v4.9..5时出现了报错syslog.warn UA2F[3874]: Received non-tcp packet. You may set wrong firewall rules.
虽此时ua2f还在努力工作，但这报错让小女子摸不着头脑，因为小女子不会找那个“wrong firewall rules”ヽ(*。>Д<)o゜
而且它打印日志打得贼快，满屏幕都是，有的干扰小女子看日志。

**Comment by Zxilly** [comment]
这个似乎是编译器的bug，试着去掉 CMakeList.txt中的 
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -ffunction-sections -fdata-sections")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,-gc-sections")

**Comment by YeWenxuan64** [comment]
可是，我是使用ui中的上传opkg安装呀，没有编译。（环境openwrt23.05.4，x86）

**Comment by Zxilly** [comment]
https://github.com/Zxilly/UA2F/releases/tag/v4.9.6
