### ISSUE TITLE
树莓派4问题

### ISSUE THREAD

**Issue by DH-FU** [Zxilly/UA2F#18]
我在树莓派4b上用这个ua2f，接入usb网卡做路由器几分钟后会导致网络中断，但用本身的网口做旁路由时不会中断

**Comment by Zxilly** [comment]
@DH-FU 你提供的信息不足以让我做出任何判断
树莓派的系统？什么形式的中断？

**Comment by DH-FU** [comment]
无法连接外网，内网可以使用，可以进路由器管理界面

**Comment by DH-FU** [comment]
有没有可能是因为usb网卡作WAN口导致的

**Comment by Zxilly** [comment]
@DH-FU 你给的信息太少了，真没法判断
