### ISSUE TITLE
掉线求助

### ISSUE THREAD

**Issue by xiaojibadada** [Zxilly/UA2F#19]
路由器是rm2100，采用lede源码编译并替换为最新的NFQUEUE。但平稳运行三天后 频繁出现掉线情况，之前日志出现过UA overflow但并未出现掉线情况，插件仅添加ua2f和rpk-ipid（移出后也出现掉线情况）。

**Comment by Zxilly** [comment]
`UA overflow`在设计中应该是永远不会出现的，如果出现了说明出现了无法预料的情况。
需要一份包含出现`UA overflow`的时间点的tcpdump抓包文件，我才有可能去排查

**Comment by xiaojibadada** [comment]
![QQ图片20210911232924](https://user-images.githubusercontent.com/84449267/132953230-ff861357-4d72-4259-83ea-e68549853293.png)
https://wwr.lanzoui.com/iUf1qtw7swd 抓包文件

**Comment by Zxilly** [comment]
![image](https://user-images.githubusercontent.com/31370133/132953563-bfa7f52b-c2ae-417d-8610-a5278efbec78.png)
我这看不懂了。。。你拿啥抓的包

**Comment by Zxilly** [comment]
resolved by: https://github.com/Zxilly/UA2F/commit/327f3129256c29cafdd2b7216e6dac0bdfa39a3f
