### ISSUE TITLE
PC端登录qq接收图片会被检测到并封号

### ISSUE THREAD

**Issue by epyc66** [Zxilly/UA2F#30]
插件为mentohust+ua2f
并且TTL等所有能在网络上查到的防封方法都已部署
登录qq之后后台接受图片也会被封
相当于PCqq几乎不能用，登陆后校园网账号就炸了
怀疑qq用来传输图片的端口下UA没被修改

**Comment by SunBK201** [comment]
建议针对QQ相关流量进行定点加密
