### ISSUE TITLE
NETFILTER_NETLINK_GLUE_CT may not be required

### ISSUE THREAD

**Issue by SunBK201** [Zxilly/UA2F#36]
ua2f without the `NETFILTER_NETLINK_GLUE_CT` flag still works fine.

**Comment by Zxilly** [comment]
https://github.com/Zxilly/UA2F/blob/0befa5981655a63fd09004aa1724b6fb7583ee93/src/ua2f.c#L460-L463

depends on `NETFILTER_NETLINK_GLUE_CT`.
It was used to check mark on packets, without this, UA2F cannot recognize if this connection has been tagged.
