### ISSUE TITLE
RM2100后台报错

### ISSUE THREAD

**Issue by HyperCherry** [Zxilly/UA2F#40]
Github Action云编译，启动ua2f被以下内容刷屏，且启动瞬间ua2f短暂生效

> Sat Dec 11 00:48:22 2021 user.notice : Try to start UA2F processor at [4397].

> Sat Dec 11 00:48:22 2021 user.notice : UA2F processor start at [4397].

> Sat Dec 11 00:48:22 2021 syslog.notice UA2F[4397]: Pipset inited.

> Sat Dec 11 00:48:22 2021 syslog.notice UA2F[4397]: UA2F has inited successful.

> Sat Dec 11 00:48:22 2021 syslog.err UA2F[4397]: Exit at breakpoint 10.

> Sat Dec 11 00:48:22 2021 user.err : Meet fatal error.[4397] dies by 256

**Comment by Zxilly** [comment]
https://github.com/Zxilly/UA2F/blob/4b06db820f3dec98533c6798a1ad12648ecb1b19/src/ua2f.c#L490
错误是在这里抛出的，但是你是第一个向我报告这个异常的。
可能是啥冲突了，或者系统内核版本低了，或者哪个库版本不对。。？可能性有点多
