### ISSUE TITLE
大佬，请问443端口真的没用办法吗，还是会检测到ua

### ISSUE THREAD

**Issue by 1161467173** [Zxilly/UA2F#46]
大佬，请问443端口真的没用办法吗，还是会检测到ua

**Comment by Zxilly** [comment]
```
uci set ua2f.firewall.handle_tls=1
uci commit ua2f
```
这样 `UA2F` 就会处理 443 端口，但是大部分情况下并不需要

**Comment by 1161467173** [comment]
但是我在路由器根目录找不到ua2f这个文件夹，运行上面第一个命令后显示entry not found，改ua功能却是正常的，去/etc/config 里面有firewall但是没有ua2f，firewall里面也没有handle_tls，我是不是应该在根目录新建ua2f.firewall

**Comment by Zxilly** [comment]
你ua2f装上了吗，或者说用的旧版本？opkg看一下

**Comment by 1161467173** [comment]
root@OpenWrt:~# opkg list ua2f
ua2f - 3.7-10

**Comment by Zxilly** [comment]
这是比较早的版本了，手动配iptables，规则 readme 有，或者更新到 `3.7-16`

**Comment by 1161467173** [comment]
iptables -t mangle -A ua2f -m connmark --mark 43 -j RETURN # 不处理标记为非 http 的流 (实验性)
这条规则注释掉是吧

**Comment by Zxilly** [comment]
不是
iptables -t mangle -A ua2f -p tcp --dport 443 -j RETURN
这个注释掉，你找的那个已经是经过检查的，是安全的
