### ISSUE TITLE
ua2f在某些网页失效

### ISSUE THREAD

**Issue by 1161467173** [Zxilly/UA2F#47]
大佬您好
比如ua.chn.moe则显示ffffffff
在https://www.atool99.com/useragent.php
则显示真实的ua，这将导致反检测失效，版本3.7-10
架构 | MediaTek MT7621 ver:1 eco:3 x 4
固件版本 | OpenWrt R21.4.18 / LuCI Master (git-21.114.56541-974fb04)
内核版本 | 5.4.117

**Comment by Zxilly** [comment]
https是安全的，不可能被检测，也无法mitm

**Comment by 1161467173** [comment]
好的谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月10日(星期天) 晚上10:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zxilly/UA2F] ua2f在某些网页失效 (Issue #47)





 
https是安全的，不可能被检测，也无法mitm
