### ISSUE TITLE
大佬你好，微信电脑版发不了图片

### ISSUE THREAD

**Issue by Carever** [Zxilly/UA2F#48]
经过排除，只要把这条给注释掉，微信电脑版就能发图片了，同时ua2f也会失效
iptables -t mangle -A ua2f -j NFQUEUE --queue-num 10010
这是为什么呢，有没有好的办法，如果设置防火墙不处理微信的地址，可能会被检测到ua

**Comment by Zxilly** [comment]
你把这个注释掉等于把na2f关了，那肯定不影响
微信估计是那个mmtls，没啥办法

**Comment by 1161467173** [comment]
哭了，哈哈哈哈哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月16日(周六) 凌晨0:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Zxilly/UA2F] 大佬你好，微信电脑版发不了图片 (Issue #48)




 
你把这个注释掉等于把na2f关了，那肯定不影响
 微信估计是那个mmtls，没啥办法

**Comment by Zxilly** [comment]
如果你能确定微信的包包含特定字符串，比如`mmtls`这种，可以通过加一条
`iptables -t mangle -A us2f -p tcp -m string --string "mmtls" --algo bm -j RETURN`
在你指出的那条前面来实现绕过
