### ISSUE TITLE
最新版本按照启动教程非常难生效

### ISSUE THREAD

**Issue by Yinsel** [Zxilly/UA2F#51]
系统日志只显示ua2f 初始化成功，查看status一直是inactive

**Comment by Zxilly** [comment]
附上一下日志和你操作的回显

**Comment by duan-1** [comment]
@Yinsel 建议把菜单 `网络` - `Turbo ACC 网络加速设置` 里面的选项都关闭试试，刚刚倒腾了一下午就搞定了

**Comment by Yinsel** [comment]
跟这个应该有很大关系！

**Comment by Yinsel** [comment]
> @Yinsel 建议把菜单 `网络` - `Turbo ACC 网络加速设置` 里面的选项都关闭试试，刚刚倒腾了一下午就搞定了

跟这个有很大关系！

**Comment by Zxilly** [comment]
是的，必须关闭硬件加速

**Comment by duan-1** [comment]
主要是文档从 Github 指向给博客，最后又指向给 notion，如果是对于纯新手来说还是有点难懂（非贬义）
