### ISSUE TITLE
以太网接口下有点奇怪

### ISSUE THREAD

**Issue by Kyaru2333** [Zxilly/UA2F#54]
已经成功编译了UA2F进OpenWrt，但是
日志是正常的
然后还出现了个很奇怪的现象
WIFI下的所有终端均已生效，无论怎么刷新（包括电脑）都不会出现UA回到原来UA的情况
物理接口下的设备，只有第一次访问是修改生效的，第二次访问时就会变回浏览器原来的UA
如果我不更换浏览器，访问第一次后更换端口，他又会生效一次，第二次刷新又会回到浏览器的UA
感觉很随机，但是以太网下第一个访问绝对时F

**Comment by Zxilly** [comment]
是不是开了硬件加速，Turbo ACC啥的

**Comment by Kyaru2333** [comment]
我没有吧TurboACC编译进去，只是编译了IPID和UA2F进去

**Comment by Kyaru2333** [comment]
[2022-09-16 22-39-33.zip](https://github.com/Zxilly/UA2F/files/9585035/2022-09-16.22-39-33.zip)
这是视频，前面那段是有线网络的，后面那段是无线网络的

**Comment by Kyaru2333** [comment]
好了，最终发现，编译时默认开了nss加速
谢谢
