### ISSUE TITLE
Couldn't load match `string':No such file or directory

### ISSUE THREAD

**Issue by Small-tailqwq** [Zxilly/UA2F#57]
使用 `service ua2f restart` 启动ua2f的话报错如下
```
root@OpenWrt:~# service ua2f restart
iptables v1.8.7 (legacy): Couldn't load match `string':No such file or directory
```
谷歌了一下好像是新版把指令替换了还是什么。
[iptables is being replaced by nftables](https://unix.stackexchange.com/questions/621397/iptables-stopped-working-with-couldnt-load-match-stateno-such-file-or-direc)
不过好像不影响使用，至少能够修改80端口的ua（用了两天被ban了，最长一次了但是还是挂了）

iptables v1.8.7、ua2f3.10，最新lean的源码来着。

**Comment by Zxilly** [comment]
应该是这个问题，不过最近没有迁移到 `nftables` 的计划
