### ISSUE TITLE
UA检测时而是全FFFFF，时而是正常UA

### ISSUE THREAD

**Issue by SoDebug** [Zxilly/UA2F#74]
在 "https://ua2.233996.xyz/" 测试UA时发现UA有时是全FFFFFFF，有时是真实UA。
![529612f825080af0](https://user-images.githubusercontent.com/30922923/234774990-3f330277-8ef9-4d55-966c-c2f3e8d2223a.png)
这里是路由器日志

**Comment by Zxilly** [comment]
https不会被修改，也无法被修改。
你应该用http测试
