### ISSUE TITLE
小概率会出现漏UA问题

### ISSUE THREAD

**Issue by Po810C** [Zxilly/UA2F#78]
通过长时间的抓包（一下午）发现，部分APP的UA会出现不被处理的情况，drcom防代理网关会因此立即检测出多设备，且阿里系应用有两个UA字段（虽然未被处理的UA不影响防检测效果），UA2F为最新commit编译

![image](https://user-images.githubusercontent.com/63584461/236888549-ef87df88-289e-4880-b812-0178f89cad40.png)
爱奇艺

![image](https://user-images.githubusercontent.com/63584461/236888632-6c1a8135-510a-417c-a137-16af9273c4f3.png)
淘宝

![image](https://user-images.githubusercontent.com/63584461/236888676-89b7c0bf-a5c8-42cb-b0c9-36f01d920251.png)
阿里云

**Comment by Po810C** [comment]
且此情况在mips和arm设备上较为常见，x86出现较少

**Comment by Zxilly** [comment]
truncated的包确实是无法处理的，而且当前的架构下也处理不了。
两个UA的。。。我想想怎么处理

**Comment by Zxilly** [comment]
如果可以的话能把truncated的包发出来看一下吗，我想想能怎么处理

**Comment by Po810C** [comment]
> 如果可以的话能把truncated的tcp包发出来看一下吗，我想想能怎么处理

已将抓包文件发送至你的邮箱

**Comment by Zxilly** [comment]
已经确定问题了，有非标准的User-Agent字段，可以加个特判解决。
