### ISSUE TITLE
最新版本出现错误

### ISSUE THREAD

**Issue by Po810C** [Zxilly/UA2F#81]
当使用自定义ua时，若ua长度超过定义值时会导致400错误

![image](https://github.com/Zxilly/UA2F/assets/63584461/d10b4773-0251-4269-84e0-23fcf67cd487)

![image](https://github.com/Zxilly/UA2F/assets/63584461/62ae1547-9b6b-4bf4-8c22-b2a83289d477)

**Comment by Po810C** [comment]
应该是填充错误

**Comment by Zxilly** [comment]
是填充错误，这个自定义UA的逻辑还要改一下😥

**Comment by Zxilly** [comment]
resolved in https://github.com/Zxilly/UA2F/commit/70aa29167ec47407abd2f6bf89ea72330fadc10
