### ISSUE TITLE
ip6tables 缺少 `--set-mark`

### ISSUE THREAD

**Issue by ArcadiaYang** [Zxilly/UA2F#82]
![image](https://github.com/Zxilly/UA2F/assets/74251722/15b94c92-a2dc-410d-9c64-00cc0328f726)

不知道是什么问题

**Comment by Zxilly** [comment]
你的ip6tables没有connmark模块

**Comment by ArcadiaYang** [comment]
me 已收到，我会尽快回复你。  闪 ~~~

**Comment by ArcadiaYang** [comment]
> 你的ip6tables没有connmark模块

抱歉，请问已经编译好且刷入路由器的固件怎么添加connmark模块呢

**Comment by ArcadiaYang** [comment]
这个是系统日志，不太会分析
Sun May 14 14:35:28 2023 daemon.err ua2f[10677]: Error relocating /usr/bin/ua2f: __difftime64: symbol not found
Sun May 14 14:35:28 2023 daemon.err ua2f[10677]: Error relocating /usr/bin/ua2f: __pselect_time64: symbol not found
Sun May 14 14:35:28 2023 daemon.err ua2f[10677]: Error relocating /usr/bin/ua2f: __time64: symbol not found
Sun May 14 14:35:28 2023 daemon.err ua2f[10677]: Error relocating /usr/bin/ua2f: __clock_gettime64: symbol not found
Sun May 14 14:35:33 2023 daemon.err ua2f[10699]: Error relocating /usr/bin/ua2f: __difftime64: symbol not found
Sun May 14 14:35:33 2023 daemon.err ua2f[10699]: Error relocating /usr/bin/ua2f: __pselect_time64: symbol not found
Sun May 14 14:35:33 2023 daemon.err ua2f[10699]: Error relocating /usr/bin/ua2f: __time64: symbol not found
Sun May 14 14:35:33 2023 daemon.err ua2f[10699]: Error relocating /usr/bin/ua2f: __clock_gettime64: symbol not found
Sun May 14 14:35:33 2023 daemon.info procd: Instance ua2f::ua2f s in a crash loop 6 crashes, 0 seconds since last crash

**Comment by ArcadiaYang** [comment]
> 这个是系统日志，不太会分析 Sun May 14 14:35:28 2023 daemon.err ua2f[10677]: Error relocating /usr/bin/ua2f: __difftime64: symbol not found Sun May 14 14:35:28 2023 daemon.err ua2f[10677]: Error relocating /usr/bin/ua2f: __pselect_time64: symbol not found Sun May 14 14:35:28 2023 daemon.err ua2f[10677]: Error relocating /usr/bin/ua2f: __time64: symbol not found Sun May 14 14:35:28 2023 daemon.err ua2f[10677]: Error relocating /usr/bin/ua2f: __clock_gettime64: symbol not found Sun May 14 14:35:33 2023 daemon.err ua2f[10699]: Error relocating /usr/bin/ua2f: __difftime64: symbol not found Sun May 14 14:35:33 2023 daemon.err ua2f[10699]: Error relocating /usr/bin/ua2f: __pselect_time64: symbol not found Sun May 14 14:35:33 2023 daemon.err ua2f[10699]: Error relocating /usr/bin/ua2f: __time64: symbol not found Sun May 14 14:35:33 2023 daemon.err ua2f[10699]: Error relocating /usr/bin/ua2f: __clock_gettime64: symbol not found Sun May 14 14:35:33 2023 daemon.info procd: Instance ua2f::ua2f s in a crash loop 6 crashes, 0 seconds since last crash

启用后，只有https网页可以正常打开，http网页无法打开

**Comment by Zxilly** [comment]
你这系统怎么没有libc的。。。

**Comment by Zxilly** [comment]
执行这个命令看一下
`ldd /usr/bin/ua2f`

**Comment by ArcadiaYang** [comment]
> 执行这个命令看一下 `ldd /usr/bin/ua2f`



> 执行这个命令看一下 `ldd /usr/bin/ua2f`

![image](https://github.com/Zxilly/UA2F/assets/74251722/6082ea25-0211-4ccc-87b4-85a55a3bef79)
z这样的

**Comment by Zxilly** [comment]
你是从release下载的，还是一起编译的

**Comment by Zxilly** [comment]
看起来像是因为musl1.2和1.1的abi不同导致的

**Comment by 1715173329** [comment]
目前 openwrt 三个 release 的 libc 版本均不一致，不是主线的话只能靠自己编译了

**Comment by ArcadiaYang** [comment]
me 已收到，我会尽快回复你。  闪 ~~~

**Comment by ArcadiaYang** [comment]
me 已收到，我会尽快回复你。  闪 ~~~
