### ISSUE TITLE
请问怎么配置，可以不处理某个ip发送的包？

### ISSUE THREAD

**Issue by aZerinChan** [Zxilly/UA2F#83]

**Comment by Zxilly** [comment]
给 iptables 的 ua2f 链添加一条 early return 的规则

**Comment by aZerinChan** [comment]
iptables -I ua2f -s 192.168.1.104 -j RETURN
请问是这样添加吗？
<img width="665" alt="image" src="https://github.com/Zxilly/UA2F/assets/125354217/78da18a2-b4ba-482b-bc9d-bc05c0b2857f">

**Comment by Zxilly** [comment]
不太清楚，我也不知道这是个什么加载顺序

**Comment by aZerinChan** [comment]
iptables -t mangle -A ua2f -d 192.168.1.104/24 -j RETURN 
参考图片里面修改的，添加了上面规则到防火墙，发现并没有生效
<img width="512" alt="image" src="https://github.com/Zxilly/UA2F/assets/125354217/3c6e620d-4382-48e6-b7d2-be6c0f4f72cf">
