### ISSUE TITLE
有空可以试试修改clash达到相同的效果吗

### ISSUE THREAD

**Issue by Easy1999** [Zxilly/UA2F#86]
我感觉ua2f使用还是比较麻烦的，需要自己编译固件，

然后想自己尝试修改clash内核，将http流量进行修改。我在clash/listener/http/proxy.go 里面对request.Header进行修改后，上传到路由器并重启openclash, 发现没有反应.

经过测试发现，openclash在一些配置下会调用clash_tun内核，这个内核代码是闭源的，开源的是clash内核代码(也就是说我替换到路由器上的内核没有被调用)，我感觉把这个问题解决了应该就可以了

**Comment by Zxilly** [comment]
和这个项目无关，再说也不是所有路由器都放得下go编译出来的东西
