### ISSUE TITLE
能否使用uci来自定义ua呢

### ISSUE THREAD

**Issue by newton-miku** [Zxilly/UA2F#93]
如题，能否使用uci命令写入配置文件来自定义ua，而非采用编译时写入源码的方式来实现呢

**Comment by Zxilly** [comment]
可以做，打算和那个自定义正则一起做，应该要挺久以后

**Comment by newton-miku** [comment]
好的，感谢大佬
另外，似乎UA2F在我的旁路由上几乎不起作用，反而是xmurp_ua能100%生效（我fork修改xmurp_ua后也能处理非80端口的非加密数据包），不清楚具体原因（猜测是xmurp_ua是内核模块，能直接hook处理网络层）
