### ISSUE TITLE
大佬，这个属于是内核版本不够吗

### ISSUE THREAD

**Issue by Megumin136** [Zxilly/UA2F#96]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-nfnetlink
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-nf-conntrack
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-nf-conntrack-netlink
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nf-conntrack-netlink found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-nf-reject
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-nf-reject6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-nf-conntrack6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-nf-nat
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-nf-log
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-nf-log6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-crypto-hash
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-crypto-crc32c
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-lib-crc32c
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-nft-core
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nft-core found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-nfnetlink-queue
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nfnetlink-queue found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857) for kmod-nft-queue
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-nft-queue found, but incompatible with the architectures configured
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for ua2f:
 *      kernel (= 5.15.134-1-ddb91608678f4c0cb7c9f48e683f8857)
 * opkg_install_cmd: Cannot install package ua2f.

**Comment by Zxilly** [comment]
是内核模块版本对不上，第1次用要连着系统一起编译，或者用官方的镜像

**Comment by Megumin136** [comment]
感谢解答
