### ISSUE TITLE
4.1.2之后的版本似乎在 红米ac2100  23.05  上不起作用，最新版本4.3.3重新编译固件也一样。

### ISSUE THREAD

**Issue by PC12138-Z** [Zxilly/UA2F#99]
![屏幕截图 2023-10-16 213219](https://github.com/Zxilly/UA2F/assets/148051137/ef05340d-65b0-4c7e-97cf-953237d2182b)
一个多月前最新版本是4.1.2时编译的就能用，在此基础上升级到4.3.3也不起作用，甚至尝试升级到4.2.2也不起作用
![屏幕截图 2023-10-16 213629](https://github.com/Zxilly/UA2F/assets/148051137/a614bfea-389c-4b8d-9e9d-40742c5ca3fc)

**Comment by Zxilly** [comment]
开下coredump，然后把生成的文件给我

**Comment by PC12138-Z** [comment]
> 然后运行一下 `nft list ruleset`，把返回值发一下

找原因了， nft 没起作用 ，把东西补全就好了，直接升级，跟重新编译也能起作用了，感谢提供思路

**Comment by Zxilly** [comment]
建议说一下改了什么，可以给别人参考

**Comment by PC12138-Z** [comment]
> 建议说一下改了什么，可以给别人参考

最简单就是直接安装firewall4，这个能用了，nft基本没问题

**Comment by PC12138-Z** [comment]
> 建议说一下改了什么，可以给别人参考

最简单就是直接安装firewall4，这个能用了，nft基本没问

**Comment by Zxilly** [comment]
但是如果没有firewall4的话应该会自动回退到iptables的，不应该出问题

**Comment by YeWenxuan64** [comment]
我这里也复现并解决了，4.3.3的ua2f，在云编译时没加多少自带软件包，所以编译出来用不了，然后小女子一气之下装上firewall4和全套iptables开头的软件包就能用了

**Comment by YeWenxuan64** [comment]
尤其iptables-nft

**Comment by Zxilly** [comment]
firewall4 应该是默认安装的吧，有点奇怪了

**Comment by Zxilly** [comment]
你们运行 `/etc/init.d/ua2f start` 会报错吗，在手动安装 `firewall4` 之前？

**Comment by YeWenxuan64** [comment]
云编译嘛，小女子不才，没选上firewall4。运行我这里（newwifi3-d2）假如没有firewall4时运行ua2f start只会报告statistics initialized，handler initialized，Cache lock initialized，Cleanup thread created，然后就不处理流量，没返回“已处理多少条tcp”啥的，去ua检测网站也是没改ua。安装firewall4后就能用了。（补充一点，有关于广告屏蔽插件与ua2f的兼容性测试报告吗，这点我这在初期部署openwrt时貌似有问题）

**Comment by YeWenxuan64** [comment]
?神奇，我这里是先安装firewall4然后ua2f就起作用了

**Comment by Zxilly** [comment]
4.3.4 已经添加修复
